name: Generate and Deploy Allure Report
description: Install Allure CLI, generate report from test results, and deploy to GitHub Pages

inputs:
  pr-number:
    description: 'Pull request number for deployment path'
    required: true
  test-status:
    description: 'Test execution status'
    required: true
  github-token:
    description: 'GitHub token for deployment'
    required: true

runs:
  using: composite
  steps:
    - name: Install Allure CLI
      shell: bash
      run: |
        wget -q https://github.com/allure-framework/allure2/releases/download/2.25.0/allure-2.25.0.tgz
        sudo tar -zxf allure-2.25.0.tgz -C /opt/
        sudo ln -sf /opt/allure-2.25.0/bin/allure /usr/bin/allure
        echo "✅ Allure CLI installed"

    - name: Generate Allure Report
      shell: bash
      run: |
        if [ -d "openframe-e2e-tests/target/allure-results" ] && [ "$(ls -A openframe-e2e-tests/target/allure-results 2>/dev/null)" ]; then
          echo "📊 Generating Allure report from test results..."
          allure generate -c openframe-e2e-tests/target/allure-results -o _site
          echo "✅ Report generated successfully"
        else
          echo "⚠️  No test results found, creating placeholder page..."
          mkdir -p _site
          cat > _site/index.html <<EOF
        <!DOCTYPE html>
        <html>
        <head>
          <title>No Test Results</title>
          <style>
            body { 
              font-family: Arial, sans-serif; 
              display: flex; 
              justify-content: center; 
              align-items: center; 
              height: 100vh; 
              margin: 0;
              background: #f5f5f5;
            }
            .container {
              text-align: center;
              padding: 40px;
              background: white;
              border-radius: 8px;
              box-shadow: 0 2px 8px rgba(0,0,0,0.1);
            }
            h1 { color: #ff6b6b; }
          </style>
        </head>
        <body>
          <div class="container">
            <h1>⚠️ No Test Results Available</h1>
            <p>Test results were not generated or could not be found.</p>
            <p><strong>PR #${{ inputs.pr-number }}</strong></p>
          </div>
        </body>
        </html>
        EOF
        fi

    - name: Deploy report to gh-pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ inputs.github-token }}
        publish_branch: gh-pages
        publish_dir: _site
        destination_dir: allure/${{ inputs.pr-number }}

    - name: Comment PR with Allure Report
      uses: marocchino/sticky-pull-request-comment@v2
      with:
        header: allure-report
        message: |
          **Allure Report** follow link:
          https://flamingo-stack.github.io/openframe-oss-tenant/allure/${{ inputs.pr-number }}/
          
          📈 **Test status:** ${{ inputs.test-status }}