name: Setup Telepresence
description: Setup JDK, install Telepresence, connect to cluster, and setup port-forwarding

runs:
  using: composite
  steps:
    - name: Set up JDK 21 for E2E tests
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: 'maven'

    - name: Install Telepresence
      shell: bash
      run: |
        sudo curl -fL https://app.getambassador.io/download/tel2oss/releases/download/v2.20.2/telepresence-linux-amd64 -o /usr/local/bin/telepresence
        sudo chmod a+x /usr/local/bin/telepresence
        echo "✅ Telepresence installed"

    - name: Connect to cluster with Telepresence
      shell: bash
      run: |
        telepresence connect
        echo "✅ Connected to cluster"

    - name: Setup port-forwarding to services
      shell: bash
      run: |
        kubectl port-forward svc/openframe-gateway -n microservices 8100:8100 > /tmp/pf-gateway.log 2>&1 &
        echo $! > /tmp/pf-gateway.pid
        sleep 5

        if ! kill -0 $(cat /tmp/pf-gateway.pid) 2>/dev/null; then
        cat /tmp/pf-gateway.log
        exit 1
        fi
        echo "✅ Port-forwarding established"